#TO CREATE LAMBDA AS CLOUDFORMATION CODE


AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
 MylambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      FunctionName: Testdemo
      MemorySize: 3008
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./index.zip
      Policies: AWSLambdaFullAccess
      Role: arn:aws:iam::641553134660:role/service-role/demo1
 MylambdaFunctiontwo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Testdemotwo
      Timeout: 900
      MemorySize: 3008
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./index.zip
      Policies: AWSLambdaFullAccess
      Role: arn:aws:iam::641553134660:role/service-role/demo1
